name: Test Data

on: pull_request

jobs:
  check_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pandas

      - name: Run script
        run: python ./tools/check_data.py ${{ github.ref_name }}